name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: CI
    env:
      # An Ethereum access point is required for some L1 StarkNet contract tests.
      # This sets it to secret values stored in the repository, which prevents
      # leaking it in code.
      PATHFINDER_ETHEREUM_HTTP_GOERLI_URL:       ${{ CI.secrets.PATHFINDER_ETHEREUM_HTTP_GOERLI_URL }}
      PATHFINDER_ETHEREUM_HTTP_GOERLI_PASSWORD:  ${{ CI.secrets.PATHFINDER_ETHEREUM_HTTP_GOERLI_PASSWORD }}
      PATHFINDER_ETHEREUM_HTTP_MAINNET_URL:      ${{ CI.secrets.PATHFINDER_ETHEREUM_HTTP_MAINNET_URL }}
      PATHFINDER_ETHEREUM_HTTP_MAINNET_PASSWORD: ${{ CI.secrets.PATHFINDER_ETHEREUM_HTTP_MAINNET_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo test --no-run --workspace
          timeout 5m cargo test -p pathfinder -- --skip rpc::tests --skip sequencer::tests
          timeout 3m cargo test -p pedersen --benches
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - run: cargo clippy --workspace --all-targets -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: cargo fmt --all -- --check

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: cargo doc --no-deps --document-private-items

  dep-sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo install cargo-sort
          cargo sort --check --workspace

  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Prepare py/
        run: |
          cd py
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install --requirement requirements-dev.txt

      - name: Test (python)
        run: |
          source py/.venv/bin/activate
          cd py
          pytest

      - name: Formatting (python)
        run: |
          source py/.venv/bin/activate
          cd py
          black --check src/

      - name: Lints (python)
        run: |
          source py/.venv/bin/activate
          cd py
          flake8 src/

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1

      - name: Integration (rust)
        run: |
          source py/.venv/bin/activate
          cargo test --no-run -p pathfinder
          timeout 5m cargo test -p pathfinder -- cairo::ext_py --ignored
